### ISSUE TITLE
_.contains function doesn't work with lodash 4.3.0

### ISSUE THREAD

**Issue by EdIzotov** [karma-runner/karma-coverage#210]
There is _.contains function is used In preprocessor.js file. But the function was renamed in 4.3.0 lodash version to _.includes.

Error I get:

[2016-02-11 14:57:02.872] [WARN] preprocess - Can not load "coverage"!
  TypeError: _.contains is not a function
    at createCoveragePreprocessor (MyProject\node_modules\kar
ma-coverage\lib\preprocessor.js:53:10)
    at Array.invoke (MyProject\node_modules\karma\node_module
s\di\lib\injector.js:75:15)
    at get (MyProject\node_modules\karma\node_modules\di\lib\
injector.js:48:43)
    at instantiatePreprocessor (MyProject\node_modules\karma\
lib\preprocessor.js:33:20)
    at Array.forEach (native)
    at MyProject\node_modules\karma\lib\preprocessor.js:49:21

**Comment by britztopher** [comment]
+1  @EdIzotov it wouldnt be a tough pull request if you did it yourself.

**Comment by dwatling** [comment]
I've added a pull request to fix this issue. https://github.com/karma-runner/karma-coverage/pull/212

**Comment by britztopher** [comment]
thanks @dwatling

**Comment by patrickkettner** [comment]
@karma-runner this can be closed, since #212 was merged
