### ISSUE TITLE
v0.4.1 breaks

### ISSUE THREAD

**Issue by mviens** [karma-runner/karma-coverage#158]
I had no issue when using v0.4.0.  After upgrading to v0.4.1, I get the following message:

WARN [preprocess]: Can not load "coverage"!
  TypeError: undefined is not a function
    at createCoveragePreprocessor (C:\Dev\projects\Tallac\web_root\node_modules\karma-coverage\lib\preprocessor.js:53:10)
    at Array.invoke (C:\Dev\projects\Tallac\web_root\node_modules\karma\node_modules\di\lib\injector.js:75:15)
    at get (C:\Dev\projects\Tallac\web_root\node_modules\karma\node_modules\di\lib\injector.js:48:43)
    at instantiatePreprocessor (C:\Dev\projects\Tallac\web_root\node_modules\karma\lib\preprocessor.js:67:37)
    at Array.forEach (native)
    at C:\Dev\projects\Tallac\web_root\node_modules\karma\lib\preprocessor.js:88:31
    at C:\Dev\projects\Tallac\web_root\node_modules\karma\lib\file_list.js:219:17
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by Dignifiedquire** [comment]
Could you add some deatails about your setup?

**Comment by nmalaguti** [comment]
It's possible that you don't have a `reporters` property defined in your configuration or that it isn't an array.

**Comment by mviens** [comment]
If I revert back to v0.4.0 then the error goes away.

I am not entirely sure what information you would like to see about the configuration.  Are you looking for the contents of any of these files:  gruntfile.js, karma.config.js, package.json

Are you looking for the output of "npm ls"?

I have installed everything through "npm install".  Other developers in our company have reported the same issue after upgrading to v0.4.1 today.

**Comment by Dignifiedquire** [comment]
It would help to see the relevant part of you grunt config and if possible as much as you can share of your karma config.

**Comment by mandekisd** [comment]
Had the same and debugging the line 53 at preprocessor.js the _.includes function is undefined.  Is that an Underscore dependency?

**Comment by Dignifiedquire** [comment]
Interesting, so it seems that you are running an outdated version of lodash. Try upgrading to the latest version of karma and see if that fixes things please. If not please provide the output from `npm ls`

**Comment by mandekisd** [comment]
I have Karma 0.12.31.  Is there a newer?

**Comment by Dignifiedquire** [comment]
yes

```
❯ npm view karma@latest version
0.12.36
```

**Comment by mandekisd** [comment]
Works!

**Comment by Dignifiedquire** [comment]
Great. There is also `karma-coverage@0.4.2` now which fixes backwards compatibility if you can't upgrade to the latest karma version yet

**Comment by Dignifiedquire** [comment]
@mviens I'm closing this for now, please reopen if the latest versions of karma + karma-coverage do not fix the issue for you.
